export const invalidValues = {
    emailWithSpace: 'testuser  rentzila@gmail.com',
    cyrillicAlphabet: 'еуіегіуккутеяшдф',
    emailWrongGmailFormat: 'testuserrentzilagmail.com',
    gmailWithoutDot: 'testuserrentzila@gmailcom',
    gmailWithoutCom: 'testuserrentzila@gmail',
    gmailWithoutGmail: 'testuserrentzila@.com',
    latinText: 'testuserrentzila',
    gmailWithExtraSymbol: 'testuserrentzila@@gmail.com',
    specialSymbols: '<>{};^',
    numbers: '123456789',
    space: ' ',
    capitalCyrillic: 'АТЭК',
    firstCapitalCyrillic: 'Атэк',
    oneCapital: 'A',
    dataWithSpaces: ['123 456', '123456 '],
    invalidData: [' ', 'abc', '!@#$%.,'],
};