export const validValues = {
    emailForInfo: 'mailto:info@rentzila.com.ua',
    dialogText: 'TEXT',
    warnDialogText: 'Внесені зміни, можливо, не буде збережено.',
    phoneNumber: '+380506743060',
    tabNames: ['основна інформація', 'фотографії', 'послуги', 'вартість', 'контакти'],
    createUnitTitle: 'Створити оголошення',
    canceledButtonText: /Скасувати/,
    categoryTitleText: /Категорія \*/,
    categorySelectText: /Виберіть категорію/,
    categoryPopupTitle: /Вибір категорії технічного засобу/,
    firstColumnElements: /Будівельна техніка/,
    secondColumnElements: /Бурові установки/,
    thirdColumnElements: /палебійні установки/,
    descriptionTitle: 'Детальний опис',
    modalNameInputTitle: /Назва моделі/,
    modalNameInputText: /Введіть назву моделі/,
    modalNameInputValue: '012345678901234',
    nextButtonText: 'Далі',
    vehicleManufacturerSectionInputValue: 'ABC',
    technicalCharacteristicsTitle: 'Технічні характеристики',
    unitNameText: /Назва оголошення \*/,
    unitNameInputFieldValue: 'abcdefghij',
    unitNameInputFieldText: /Введіть назву оголошення/,
    vehicleLocationDivisionTitle: /Місце розташування технічного засобу \*/,
    vehicleLocationDivisionInputText: /Виберіть на мапі/,
    mapPopupTitle: /Техніка на мапі/,
    popupAddress: /Київ, вулиця Володимирська 21\/20 Україна, Київська область/,
    vehicleManufacturerSectionTitle: /Виробник транспортного засобу \*/,
    vehicleManufacturerSectionInputText: /Введіть виробника транспортного засобу/,
    vehicleManufacturerSectionInputMessage: /На жаль, виробника “123456789“ не знайдено в нашій базі./,
    specialEquipmentName: 'посівна та садильна техніка',
    serviceName: 'Посів технічних та зернових культур',
    srcImageValue: /data:image/,
    imageUploadTitle: /Фото технічного засобу \*/,
    imageDivClueText: /Додайте в оголошення від 1 до 12 фото технічного засобу розміром до 20 МВ у форматі .jpg, .jpeg, .png. Перше фото буде основним./,
    imageFirstContainerText: /Головне/,
    photoTabNextButtonText: /Далі/,
    firstServisesBodyTabContainerText: /Створити оголошення/,
    secondServisesBodyTabContainerText: /основна інформація/,
    thirdServisesBodyTabContainerText: /фотографії/,
    fourthServisesBodyTabContainerText: /послуги/,
    fifthServisesBodyTabContainerText: /вартість/,
    sixthServisesBodyTabContainerText: /контакти/,
    profilePagePrevButtonText: /Назад/,
    profilePageSaveBtnText: /Зрозуміло/,
};